# Generated by Django 2.2.15 on 2020-09-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='orderitemle',
        ),
        migrations.AddField(
            model_name='variation',
            name='orderitemle',
            field=models.ManyToManyField(blank=True, null=True, to='Main.OrderItem'),
        ),
    ]
