# Generated by Django 2.2.15 on 2020-09-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20200913_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='highest_price',
            field=models.FloatField(default=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
