# Generated by Django 2.2.15 on 2020-09-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20200917_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('S', 'Single 120 x 200'), ('Q', 'Queen 160 x 200'), ('K', 'King 180 x 200'), ('SK', 'Super King 200 x 200'), ('S', 'Set')], editable=False, max_length=2, null=True),
        ),
    ]
