# Generated by Django 2.2.15 on 2020-09-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20200917_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='orderitemle',
        ),
    ]
