# Generated by Django 2.2.15 on 2020-09-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_remove_variation_orderitemle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='short_desc',
        ),
    ]
