# Generated by Django 2.2.15 on 2020-09-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_remove_variation_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='highest_price',
            field=models.FloatField(default=1000),
        ),
    ]
