# Generated by Django 2.2.15 on 2020-09-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20200917_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(to='Main.Variation'),
        ),
    ]
