# Generated by Django 2.2.15 on 2020-09-26 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_orderitem_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variations',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Variation'),
        ),
    ]
