# Generated by Django 2.2.15 on 2020-09-26 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20200926_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='price',
            new_name='pricy',
        ),
    ]
