# Generated by Django 2.2.15 on 2020-09-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20200926_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variations',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(to='Main.Variation'),
        ),
    ]
