# Generated by Django 2.2.15 on 2020-10-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20201003_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='title',
            new_name='Title',
        ),
    ]
