# Generated by Django 2.2.15 on 2020-10-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20201003_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='pricy',
            field=models.FloatField(),
        ),
    ]
