# Generated by Django 2.2.15 on 2020-10-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_order_vari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(blank=True, null=True, to='Main.Variation'),
        ),
    ]
