# Generated by Django 2.2.15 on 2020-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20201003_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='qty',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
