# Generated by Django 2.2.15 on 2020-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_variation_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vari',
        ),
        migrations.AddField(
            model_name='order',
            name='vari',
            field=models.ManyToManyField(blank=True, null=True, to='Main.Variation'),
        ),
    ]
