# Generated by Django 2.2.15 on 2020-10-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_auto_20201007_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='qty',
        ),
    ]
