# Generated by Django 2.2.15 on 2020-10-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_remove_variation_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
