# Generated by Django 2.2.15 on 2020-10-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_auto_20201008_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(related_name='OrItVa', to='Main.Variation'),
        ),
    ]
