# Generated by Django 2.2.15 on 2020-10-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_auto_20201009_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mohammed', models.CharField(max_length=200, verbose_name='Moha')),
                ('fil', models.FileField(upload_to='moha/%Y/%m/%d')),
            ],
        ),
    ]
