# Generated by Django 2.2.15 on 2020-10-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_mat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mat',
        ),
    ]
