# Generated by Django 2.2.15 on 2020-10-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_variation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='slug',
        ),
    ]
