# Generated by Django 2.2.15 on 2020-10-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_auto_20201021_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variations',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(related_name='OrItVa', to='Main.Variation'),
        ),
    ]
