# Generated by Django 2.2.15 on 2020-10-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(to='Main.Variation'),
        ),
    ]
