# Generated by Django 2.2.15 on 2020-10-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0030_auto_20201022_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='v',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vees', to='Main.Variation'),
        ),
    ]
