# Generated by Django 2.2.15 on 2020-10-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_orderitem_v'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='v',
        ),
    ]
