# Generated by Django 2.2.15 on 2020-11-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_remove_orderitem_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_category',
            field=models.CharField(choices=[('T', 'Towels'), ('BS', 'bedsheets'), ('S', 'Sateen'), ('D', 'Duvet'), ('V', 'Variety')], default='V', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_de',
            field=models.CharField(max_length=250, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Product Name'),
        ),
    ]
