# Generated by Django 2.2.15 on 2020-11-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_auto_20201102_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_category',
            field=models.CharField(choices=[('T', 'Towels'), ('BS', 'Bedsheets'), ('S', 'Sateen'), ('D', 'Duvet'), ('V', 'Variety'), ('P', 'Percale'), ('PC', 'Pillowcases')], default='V', max_length=2),
        ),
    ]
