# Generated by Django 2.2.15 on 2020-11-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0036_auto_20201102_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, help_text='this field is optional', null=True, upload_to='Egypt_fabrics'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, help_text='this field is optional', null=True, upload_to='Egypt_fabrics'),
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.ImageField(blank=True, help_text='this field is optional', null=True, upload_to='Egypt_fabrics'),
        ),
    ]
