# Generated by Django 2.2.15 on 2020-11-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0037_auto_20201103_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='highest_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image4',
        ),
    ]
