# Generated by Django 2.2.15 on 2020-11-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0041_auto_20201104_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Si', 'Single 120 x 200'), ('Q', 'Queen 160 x 200'), ('K', 'King 180 x 200'), ('SK', 'Super King 200 x 200'), ('S', 'Set'), ('PS', 'Standard  51 x 56'), ('PQ', 'Queen size  51 x 76'), ('PK', 'King size  51 x 92'), ('PB', 'Body size  51 x 137 ')], default='S', max_length=2, null=True, verbose_name='1:category'),
        ),
    ]
