# Generated by Django 2.2.15 on 2020-11-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0043_auto_20201106_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Si', 'Single 120 x 200'), ('Q', 'Queen 160 x 200'), ('K', 'King 180 x 200'), ('SK', 'Super King 200 x 200'), ('S', 'Set'), ('PS', 'Standard  51 x 56'), ('PQ', 'Queen size  51 x 76'), ('PK', 'King size  51 x 92'), ('PB', 'Body size  51 x 137 ')], default='S', help_text='sizes and quantity', max_length=2, verbose_name='1-category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_category',
            field=models.CharField(choices=[('T', 'Towels'), ('BS', 'Bedsheets'), ('S', 'Sateen'), ('D', 'Duvet'), ('V', 'Variety'), ('P', 'Percale'), ('PC', 'Pillowcases')], default='V', help_text='Products Dropdown in Egypt Fabrics Navbar', max_length=2, verbose_name='2-Product Category'),
        ),
    ]
