# Generated by Django 2.2.15 on 2020-11-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0044_auto_20201106_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Company',
            field=models.CharField(blank=True, editable=False, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='5- description '),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='5- description '),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_de',
            field=models.TextField(null=True, verbose_name='5- description '),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_en',
            field=models.TextField(null=True, verbose_name='5- description '),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='Egypt_fabrics', verbose_name='1- image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, help_text='this field is optional', null=True, upload_to='Egypt_fabrics', verbose_name='2- image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, help_text='this field is optional', null=True, upload_to='Egypt_fabrics', verbose_name='3- image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(verbose_name='4- Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(help_text='Random input, it is better to add the category of the product here for example : Towels ', max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=250, verbose_name='3-Product Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='3-Product Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_de',
            field=models.CharField(max_length=250, null=True, verbose_name='3-Product Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='3-Product Name'),
        ),
    ]
