# Generated by Django 2.2.15 on 2020-11-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0046_auto_20201106_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='variation',
            new_name='variations',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_category',
        ),
        migrations.AddField(
            model_name='item',
            name='highest_price',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Company',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('S', 'Single 120 x 200'), ('Q', 'Queen 160 x 200'), ('K', 'King 180 x 200'), ('SK', 'Super King 200 x 200'), ('S', 'Set')], editable=False, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='Egypt_fabrics'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(help_text='random input', max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
