# Generated by Django 2.2.15 on 2020-11-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0047_auto_20201114_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='variations',
            new_name='variation',
        ),
        migrations.AlterField(
            model_name='address',
            name='govs',
            field=models.CharField(blank=True, choices=[('', 'For Egypt Only'), ('6th of October', '6th of October'), ('Al Sharqia', 'Al Sharqia'), ('alexandria', 'alexandria'), ('Aswan', 'Aswan'), ('Asyut', 'Asyut'), ('Beheira', 'Beheira'), ('Beni Suef', 'Beni Suef'), ('Cairo', 'Cairo'), ('Dakahlia', 'Dakahlia'), ('Damietta ', 'Damietta '), ('Faiyum', 'Faiyum'), ('Gharbia', 'Gharbia'), ('Giza', 'Giza'), ('Ismailia', 'Ismailia'), ('Kafr El Sheikh', 'Kafr El Sheikh'), ('Luxor', 'Luxor'), ('Matruh', 'Matruh'), ('Minya', 'Minya'), ('Monufia', 'Monufia'), ('New Valley', 'New Valley'), ('North Sinai', 'North Sinai'), ('Port Said', 'Port Said'), ('Qalyubia ', 'Qalyubia '), ('Qena', 'Qena'), ('Red Sea', 'Red Sea'), ('Sharqia ', 'Sharqia '), ('Sohag', 'Sohag'), ('South Sinai', 'South Sinai'), ('Suez', 'Suez')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
