# Generated by Django 2.2.15 on 2020-11-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0049_auto_20201118_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, help_text='this field is optional', null=True, upload_to='Egypt_fabrics', verbose_name='2- image'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, help_text='this field is optional', null=True, upload_to='Egypt_fabrics', verbose_name='3- image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='Egypt_fabrics', verbose_name='1- image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
