# Generated by Django 2.2.15 on 2020-11-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0054_auto_20201118_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='Egypt_fabrics/default2.png', help_text='this field is optional', upload_to='Egypt_fabrics', verbose_name='2- image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(default='Egypt_fabrics/default1.jpeg', help_text='this field is optional', upload_to='Egypt_fabrics', verbose_name='3- image'),
        ),
    ]
