# Generated by Django 2.2.15 on 2020-11-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0056_auto_20201118_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='highest_price',
        ),
    ]
