# Generated by Django 2.2.15 on 2020-11-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0057_remove_item_highest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('size', 'size')], default='size', editable=False, max_length=200),
        ),
    ]
