# Generated by Django 2.2.15 on 2020-11-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0058_auto_20201118_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='Title',
            field=models.CharField(help_text='the size of the item', max_length=200, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='pricy',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
