# Generated by Django 2.2.15 on 2020-11-18 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0059_auto_20201118_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='itemy',
            field=models.ForeignKey(help_text='select the item that you want to add variation to.', on_delete=django.db.models.deletion.CASCADE, to='Main.Item', verbose_name='Item'),
        ),
    ]
