# Generated by Django 2.2.15 on 2020-11-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0060_auto_20201118_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='Title_ar',
            field=models.CharField(help_text='the size of the item', max_length=200, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='variation',
            name='Title_de',
            field=models.CharField(help_text='the size of the item', max_length=200, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='variation',
            name='Title_en',
            field=models.CharField(help_text='the size of the item', max_length=200, null=True, verbose_name='Size'),
        ),
    ]
