# Generated by Django 2.2.15 on 2020-11-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0061_auto_20201118_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Monty', to='Main.Variation'),
        ),
    ]
