# Generated by Django 2.2.15 on 2020-11-19 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0062_orderitem_ma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ma',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Variation'),
        ),
    ]
