# Generated by Django 2.2.15 on 2020-11-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0063_auto_20201119_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ManyToManyField(to='Main.Variation'),
        ),
    ]
