# Generated by Django 2.2.15 on 2020-11-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0064_auto_20201119_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('S', 'Single 120 x 200'), ('Q', 'Queen 160 x 200'), ('K', 'King 180 x 200'), ('SK', 'Super King 200 x 200'), ('S', 'Set')], default='S', editable=False, help_text='sizes and quantity', max_length=2, null=True, verbose_name='1-category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_category',
            field=models.CharField(blank=True, choices=[('T', 'Towels'), ('BS', 'Bedsheets'), ('V', 'Variety'), ('PC', 'Pillowcases')], default='V', editable=False, help_text='Products Dropdown in Egypt Fabrics Navbar', max_length=2, null=True, verbose_name='2-Product Category'),
        ),
    ]
