# Generated by Django 2.2.15 on 2020-11-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0065_auto_20201124_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='title',
        ),
    ]
