# Generated by Django 2.2.15 on 2020-11-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0067_auto_20201125_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
    ]
