# Generated by Django 2.2.15 on 2020-12-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0068_auto_20201125_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id']},
        ),
    ]
